name: mybeshop
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_web_plugins:
    sdk: flutter
  get: ^4.6.6
  line_awesome_flutter: ^2.0.0
  lottie: ^2.7.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  url_launcher: ^6.2.4
  dropdown_search: ^5.0.6
  input_quantity: ^2.2.0
  intl:

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lotties/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  fonts:
    - family: Alexandria
      fonts:
        - asset: assets/fonts/alex/Alexandria-Regular.ttf
          weight: 400
        - asset: assets/fonts/alex/Alexandria-Medium.ttf
          weight: 500
        - asset: assets/fonts/alex/Alexandria-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/alex/Alexandria-Bold.ttf
          weight: 700
        - asset: assets/fonts/alex/Alexandria-ExtraBold.ttf
          weight: 800
